### ISSUE TITLE
Failed to connect to localhost port

### ISSUE THREAD

**Issue by nlotambov** [eroji/rtsp2mjpg#12]
I can't connect, no matter what port I specify, everything is useless
`orangepi@orangepipc:~/rtsp2mjpg$ docker-compose -f docker-compose.yaml-armhf up -d
Pulling rtsp2mjpg (eroji/rtsp2mjpg:armhf)...
armhf: Pulling from eroji/rtsp2mjpg
be762b1acc36: Pull complete
65fd87036744: Pull complete
360887e2821c: Pull complete
e48b55f70cc1: Pull complete
0fcb2159076a: Pull complete
34f9891839e7: Pull complete
87f813bf9d48: Pull complete
5715d495329c: Pull complete
119d4a4477c6: Pull complete
2e7b558f1e6b: Pull complete
3626efc38131: Pull complete
76d75baaec73: Pull complete
d432592076bd: Pull complete
b62f90bbd45e: Pull complete
9c44e9bec724: Pull complete
4ad28e749283: Pull complete
79356413a041: Pull complete
404f6c97ed63: Pull complete
377725b2b18b: Pull complete
ad493977b52e: Pull complete
0e416af96602: Pull complete
48556e82b4cb: Pull complete
e678074cfd52: Pull complete
Digest: sha256:a5ff0820948e8887f104a18078b6fcfcbc2e6906434fd727b04ec9b8245d3a4d
Status: Downloaded newer image for eroji/rtsp2mjpg:armhf
Creating rtsp2mjpg_rtsp2mjpg_1 ... done

orangepi@orangepipc:~/rtsp2mjpg$ curl -f http://localhost:8090/still.jpg
curl: (7) Failed to connect to localhost port 8090: Connection refused

docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.20-sunxi
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 998.4MiB
 Name: orangepipc
 ID: 7QSX:22J6:PRGE:ZSBB:EN2C:UNXN:JFFF:2ZCE:BEBX:DVLY:ZMNW:NO3P
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

docker -v
Docker version 19.03.13, build 4484c46
`

docker-compose.yaml-armhf
version: '3'
services:
  rtsp2mjpg:
    image: eroji/rtsp2mjpg:armhf
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Uncomment below if you want to override default ffserver.conf
      # - ./ffserver.conf:/etc/ffserver.conf:ro
    environment:
      # Override the env vars below as needed
      RTSP_URL: rtsp://192.168.1.37:8554/unicast
      FFSERVER_LOG_LEVEL: error
      FFMPEG_LOG_LEVEL: info
      FFMPEG_INPUT_OPTS: -nostats -use_wallclock_as_timestamps 1 -r 15 -thread_queue_size 2048 -probesize 50M -analyzeduration 100M
      FFMPEG_OUTPUT_OPTS: -vf fps=15 -video_track_timescale 90000 -c:v h264_omx
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090/still.jpg --max-time 1 --output /dev/null || exit 1"]
      interval: 15s
      timeout: 1s
      retries: 3

**Comment by eroji** [comment]
What do the stdout of the container show? Does the container stay up with your provided docker-compose above?

**Comment by nlotambov** [comment]
Sorry I'm a beginner, how can I see this?

**Comment by eroji** [comment]
Do `docker ps -a` and see if the container is staying running. Do `docker logs -f <uid>` to see the log/stdout of the container. You'll need to search for Docker howto's to learn some basics on troubleshooting your container.
