### ISSUE TITLE
Using rtsp2mjpg for HTML5 compatibile video stream

### ISSUE THREAD

**Issue by oliveres** [eroji/rtsp2mjpg#13]
Hi, your rtsp2mjpg project is perfect, everything is working as expected. No I can view Hikvision 4K IP camera on any browser or device.

BUT if I stream mjpg with high resolution and framerate, this is not usable, because I'm receiving about 80 Mbit/s of data. I spend last night to modify configuration of the rtsp2mjpg to serve WEBM with VP9 codec. I'm not know if I did some mistake, but I can see only first frame of video and it freeze.

EDIT: I can made this to work, but only 640x360 and 5 FPS. Everything more than this resolution cause that stream in browser seems to be playing, but image is freezed.

Do you think it's possible to make it work just by editing the codec and format in ffserver.conf file?

Thank you.

**Comment by eroji** [comment]
Unfortunately I am not an expert with ffserver configuration, so you'll need to do some experimenting with it yourself, but probably difficult to keep up with 4k webcam.
