### ISSUE TITLE
Streams have no sound

### ISSUE THREAD

**Issue by f5AFfMhv** [eroji/rtsp2mjpg#16]
Is it possible to watch stream with audio?

**Comment by f5AFfMhv** [comment]
Managed to stream rtsp to webm with sound. Found `ffserver.conf` example which worked for me [here](https://stackoverflow.com/questions/35398288/how-to-make-ffserver-working-well-in-real-time)

**Comment by hendymen** [comment]
@f5AFfMhv Could you share your ffserver.conf and/or steam.sh files? i don't seem to get it to work.

Thanks alot!!
