### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by omsiqveland** [eroji/rtsp2mjpg#20]
Any chance you could add support for SSL to this container, such that the mjpeg stream is output on a secure https:// url?

I want to integrate a camera stream in my other webpage which is hosted on a secure server (https).
When trying to access content from unencrypted sources Chrome flags my page as unsecure and gives me a warning.
Hence, it would be great if the video could be output on a https url.

**Comment by eroji** [comment]
You can do this with nginx reverse proxy and configuring SSL certificate. This is not handled by the ffserver used to serve the video stream. There are plenty of guides online on how to configure nginx.
