### ISSUE TITLE
there is error when i try to open the live link

### ISSUE THREAD

**Issue by scarrrr316** [eroji/rtsp2mjpg#4]

**Comment by scarrrr316** [comment]
![image](https://user-images.githubusercontent.com/43269183/75734829-fbf3de00-5d33-11ea-8fba-a24bcc81a2ab.png)
it seem that rtsp2mjpg serves start up successfully

but when i try to open the link in google chrome ，it show something in below picture
![image](https://user-images.githubusercontent.com/43269183/75735011-74f33580-5d34-11ea-8a49-68eb658cb3f4.png)

can you tell me how to fix it？

**Comment by scarrrr316** [comment]
I just change the rtsp link in .yaml file and the port because port80 is used by hapoxy

**Comment by eroji** [comment]
I assume you are using `docker-compose.yaml-armhf`? If so, it would be serving on port 8090 and not 80. Your screenshot shows you have nginx container as well, which suggests you are using the `docker-compose.yaml` which refers to x86_64 images. This would not start up on Pi because the CPU architecture is entirely different.

Here is how I launch it on my Pi. You can see that it binds to port 8090 after `docker-compose`.
```
root@octopi:~/rtsp2mjpg# netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      737/sshd            
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      27931/python2       
tcp6       0      0 :::80                   :::*                    LISTEN      738/haproxy         
tcp6       0      0 :::22                   :::*                    LISTEN      737/sshd            
tcp6       0      0 :::443                  :::*                    LISTEN      738/haproxy         
root@octopi:~/rtsp2mjpg# docker-compose -f docker-compose.yaml-armhf up -d
Creating network "rtsp2mjpg_default" with the default driver
Creating rtsp2mjpg_rtsp2mjpg_1 ... done
root@octopi:~/rtsp2mjpg# netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      737/sshd            
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      27931/python2       
tcp6       0      0 :::80                   :::*                    LISTEN      738/haproxy         
tcp6       0      0 :::22                   :::*                    LISTEN      737/sshd            
tcp6       0      0 :::8090                 :::*                    LISTEN      28503/docker-proxy  
tcp6       0      0 :::443                  :::*                    LISTEN      738/haproxy         
```

**Comment by scarrrr316** [comment]
![image](https://user-images.githubusercontent.com/43269183/75763845-dee0fe80-5d77-11ea-9487-9c9c9aca6924.png)
そうてすね ，thank you，I don’t know that different yaml file are use in different system，because the introduction didn’t tell me，ha ha，hope it work

**Comment by scarrrr316** [comment]
![image](https://user-images.githubusercontent.com/43269183/75766070-86136500-5d7b-11ea-8e76-2ecfd453540c.png)
emmmmmmm，it has a new error now

**Comment by scarrrr316** [comment]
it has 1 min delay ,is it normal？

**Comment by eroji** [comment]
1 min certainly seems excessive. What Pi model are you using?

**Comment by scarrrr316** [comment]
> 1 min certainly seems excessive. What Pi model are you using? On a Pi4, I was seeing relatively realtime transcode.

I am using raspberry pi 3b+，I dont know why it just have maybe 1 frames per 2-4 second and large delay.And also it start fail somtime ,can you give me another contact method of you？,e.g：telegram，discord，i think using github to contact is inconvenient，thx

**Comment by scarrrr316** [comment]
hi？？

**Comment by eroji** [comment]
I been out-of-town. I don't have any other contact method unless you do.

**Comment by scarrrr316** [comment]
what is your email addr？i want to send my contact mehtod to you。And what contact method do you want to use？

**Comment by eroji** [comment]
I added my email in my profile.

**Comment by eroji** [comment]
Closing this ticket since this is not a code issue.

**Comment by scarrrr316** [comment]
i have sant an email to you，did you receive it？

**Comment by eroji** [comment]
No. Can you put your email in your profile. I'll try and email you instead.

**Comment by scarrrr316** [comment]
i have put my contact method in my profile .and  i am interest on your name，are you Chinese，haha（chen is a common last name in chinese）？你是華人嗎

**Comment by scarrrr316** [comment]
emmm

**Comment by eroji** [comment]
I added you on Discord. Didn't get any response yet.

**Comment by scarrrr316** [comment]
sorry，i didnt check it
