### ISSUE TITLE
Blank Feed

### ISSUE THREAD

**Issue by rberrill** [eroji/rtsp2mjpg#5]
I have this docker container installed on a raspberry pi 3 with wifi.  The container stands up just fine and I was able to populate all the data and confirmed that it's in the environment variables. When I go to the stream in my browser (http://serverip:8090/live.mjpg) the page loads with no error and appears to be streaming but all I get is a blank screen.

I tested the same camera (Wyze Cam v2) using the same rstp://username:password@192.168.86.201/live in VLC and it streams just fine without issue.  Video looks fine and streams in real time.  Any idea what I might need to tweak?

**Comment by eroji** [comment]
I assume you are using docker-compose with `docker-compose.yaml-armhf` and configured the URL inside the file? If so, does the container start up and stay up without any crash loop behavior? Also, what does the logs in the container say?
